import type { ParameterMeta } from '../types';

export const PARAMETER_DEFINITIONS: ParameterMeta[] = [
  // ============================================================
  //  通用参数 (General)
  // ============================================================
  {
    key: 'model',
    flag: '-m',
    fullFlag: '--model',
    category: 'general',
    label: '模型路径',
    description: '指定加载的模型文件路径，支持 GGUF 格式的模型文件',
    type: 'file',
    placeholder: '/path/to/model.gguf',
  },
  {
    key: 'alias',
    flag: '-a',
    fullFlag: '--alias',
    category: 'general',
    label: '模型别名',
    description: '为模型设置一个别名，在日志和 API 响应中显示',
    type: 'string',
    placeholder: 'my-model',
  },
  {
    key: 'threads',
    flag: '-t',
    fullFlag: '--threads',
    category: 'general',
    label: '线程数',
    description: '指定用于推理的计算线程数量，通常设置为 CPU 物理核心数',
    type: 'number',
    defaultValue: 8,
    validation: { min: 1, max: 128, step: 1 },
  },
  {
    key: 'threads-batch',
    flag: '-tb',
    fullFlag: '--threads-batch',
    category: 'general',
    label: '批处理线程数',
    description: '指定批处理阶段的线程数，默认与 --threads 相同',
    type: 'number',
    defaultValue: 8,
    validation: { min: 1, max: 128, step: 1 },
  },
  {
    key: 'ctx-size',
    flag: '-c',
    fullFlag: '--ctx-size',
    category: 'general',
    label: '上下文大小',
    description: '设置模型的最大上下文长度（token 数），影响可处理的文本长度',
    type: 'number',
    defaultValue: 2048,
    validation: { min: 256, max: 131072, step: 256 },
  },
  {
    key: 'n-gpu-layers',
    flag: '-ngl',
    fullFlag: '--n-gpu-layers',
    category: 'general',
    label: 'GPU 层数',
    description: '指定卸载到 GPU 的模型层数，-1 表示全部卸载到 GPU',
    type: 'number',
    defaultValue: 0,
    validation: { min: -1, max: 200, step: 1 },
  },
  {
    key: 'main-gpu',
    flag: '-mg',
    fullFlag: '--main-gpu',
    category: 'general',
    label: '主 GPU',
    description: '指定主 GPU 设备索引，用于张量分配和 KV 缓存',
    type: 'number',
    defaultValue: 0,
    validation: { min: 0, max: 16, step: 1 },
  },
  {
    key: 'tensor-split',
    flag: '-ts',
    fullFlag: '--tensor-split',
    category: 'general',
    label: '张量拆分',
    description: '指定在多个 GPU 间拆分张量的比例，逗号分隔',
    type: 'string',
    placeholder: '0.5,0.5',
  },
  {
    key: 'batch-size',
    flag: '-b',
    fullFlag: '--batch-size',
    category: 'general',
    label: '批处理大小',
    description: '指定批处理的最大 token 数量，影响推理吞吐量',
    type: 'number',
    defaultValue: 2048,
    validation: { min: 1, max: 65536, step: 1 },
  },
  {
    key: 'ubatch-size',
    flag: '-ub',
    fullFlag: '--ubatch-size',
    category: 'general',
    label: '物理批处理大小',
    description: '指定物理批处理的最大 token 数量，影响显存占用',
    type: 'number',
    defaultValue: 512,
    validation: { min: 1, max: 65536, step: 1 },
  },
  {
    key: 'mlock',
    flag: '',
    fullFlag: '--mlock',
    category: 'general',
    label: '锁定内存',
    description: '将模型锁定在物理内存中，防止被交换到磁盘，可提高性能',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'no-mmap',
    flag: '',
    fullFlag: '--no-mmap',
    category: 'general',
    label: '禁用内存映射',
    description: '禁用内存映射文件加载方式，使用传统方式加载模型',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'numa',
    flag: '',
    fullFlag: '--numa',
    category: 'general',
    label: 'NUMA 优化',
    description: '启用 NUMA（非统一内存访问）优化，多路 CPU 系统建议开启',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'flash-attn',
    flag: '-fa',
    fullFlag: '--flash-attn',
    category: 'general',
    label: 'Flash Attention',
    description: '启用 Flash Attention 加速，可降低显存占用并提升推理速度',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'no-kv-offload',
    flag: '-nkvo',
    fullFlag: '--no-kv-offload',
    category: 'general',
    label: '禁用 KV 卸载',
    description: '禁用 KV 缓存卸载到 GPU，KV 缓存将保留在 CPU 内存中',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'cache-type-k',
    flag: '-ctk',
    fullFlag: '--cache-type-k',
    category: 'general',
    label: 'K 缓存类型',
    description: '指定 K 缓存的数据类型，可选 f16 或 q8_0，影响显存和精度',
    type: 'select',
    defaultValue: 'f16',
    options: [
      { label: 'f16 (半精度)', value: 'f16' },
      { label: 'q8_0 (8位量化)', value: 'q8_0' },
    ],
    advanced: true,
  },
  {
    key: 'cache-type-v',
    flag: '-ctv',
    fullFlag: '--cache-type-v',
    category: 'general',
    label: 'V 缓存类型',
    description: '指定 V 缓存的数据类型，可选 f16 或 q8_0，影响显存和精度',
    type: 'select',
    defaultValue: 'f16',
    options: [
      { label: 'f16 (半精度)', value: 'f16' },
      { label: 'q8_0 (8位量化)', value: 'q8_0' },
    ],
    advanced: true,
  },
  {
    key: 'lora',
    flag: '',
    fullFlag: '--lora',
    category: 'general',
    label: 'LoRA 适配器',
    description: '加载 LoRA 适配器文件，用于微调后的模型推理',
    type: 'file',
    placeholder: '/path/to/lora-adapter.gguf',
    advanced: true,
  },
  {
    key: 'lora-scaled',
    flag: '',
    fullFlag: '--lora-scaled',
    category: 'general',
    label: '缩放 LoRA 适配器',
    description: '加载带缩放因子的 LoRA 适配器文件，格式：文件路径+缩放比例',
    type: 'string',
    placeholder: '/path/to/lora.gguf:0.5',
    advanced: true,
  },
  {
    key: 'control-vector',
    flag: '',
    fullFlag: '--control-vector',
    category: 'general',
    label: '控制向量',
    description: '加载控制向量文件，用于控制生成方向，可指定缩放比例',
    type: 'file',
    placeholder: '/path/to/control.gguf',
    advanced: true,
  },
  {
    key: 'check-tensors',
    flag: '',
    fullFlag: '--check-tensors',
    category: 'general',
    label: '检查张量',
    description: '加载模型时检查所有张量是否完整，用于调试和验证',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'override-kv',
    flag: '',
    fullFlag: '--override-kv',
    category: 'general',
    label: '覆盖 KV 元数据',
    description: '覆盖模型文件中的 KV 元数据键值对，格式：键=类型=值',
    type: 'string',
    placeholder: 'key=int:42',
    advanced: true,
  },
  {
    key: 'rope-scaling',
    flag: '',
    fullFlag: '--rope-scaling',
    category: 'general',
    label: 'RoPE 缩放类型',
    description: '指定 RoPE 位置编码的缩放方式，支持 linear 和 yarn',
    type: 'select',
    options: [
      { label: '线性 (linear)', value: 'linear' },
      { label: 'YaRN', value: 'yarn' },
    ],
    advanced: true,
  },
  {
    key: 'rope-scale',
    flag: '',
    fullFlag: '--rope-scale',
    category: 'general',
    label: 'RoPE 缩放因子',
    description: '设置 RoPE 频率的缩放因子，用于扩展上下文长度',
    type: 'number',
    defaultValue: 1.0,
    validation: { min: 0.1, max: 100, step: 0.1 },
    advanced: true,
  },
  {
    key: 'rope-freq-base',
    flag: '',
    fullFlag: '--rope-freq-base',
    category: 'general',
    label: 'RoPE 基频',
    description: '设置 RoPE 位置编码的基础频率值',
    type: 'number',
    defaultValue: 10000.0,
    validation: { min: 1, max: 1000000, step: 1 },
    advanced: true,
  },
  {
    key: 'rope-freq-scale',
    flag: '',
    fullFlag: '--rope-freq-scale',
    category: 'general',
    label: 'RoPE 频率缩放',
    description: '设置 RoPE 频率的线性缩放因子',
    type: 'number',
    defaultValue: 1.0,
    validation: { min: 0.1, max: 100, step: 0.1 },
    advanced: true,
  },
  {
    key: 'yarn-orig-ctx',
    flag: '',
    fullFlag: '--yarn-orig-ctx',
    category: 'general',
    label: 'YaRN 原始上下文',
    description: '设置 YaRN 缩放时模型的原始上下文大小',
    type: 'number',
    defaultValue: 2048,
    validation: { min: 256, max: 131072, step: 256 },
    advanced: true,
  },
  {
    key: 'yarn-ext-factor',
    flag: '',
    fullFlag: '--yarn-ext-factor',
    category: 'general',
    label: 'YaRN 扩展因子',
    description: '设置 YaRN 上下文扩展因子',
    type: 'number',
    defaultValue: 1.0,
    validation: { min: 1, max: 100, step: 0.1 },
    advanced: true,
  },
  {
    key: 'yarn-attn-factor',
    flag: '',
    fullFlag: '--yarn-attn-factor',
    category: 'general',
    label: 'YaRN 注意力因子',
    description: '设置 YaRN 注意力缩放因子',
    type: 'number',
    defaultValue: 1.0,
    validation: { min: 0.1, max: 100, step: 0.1 },
    advanced: true,
  },
  {
    key: 'yarn-beta-slow',
    flag: '',
    fullFlag: '--yarn-beta-slow',
    category: 'general',
    label: 'YaRN Beta 慢速',
    description: '设置 YaRN 慢速频率波段的 beta 值',
    type: 'number',
    defaultValue: 1.0,
    validation: { min: 0.1, max: 100, step: 0.1 },
    advanced: true,
  },
  {
    key: 'yarn-beta-fast',
    flag: '',
    fullFlag: '--yarn-beta-fast',
    category: 'general',
    label: 'YaRN Beta 快速',
    description: '设置 YaRN 快速频率波段的 beta 值',
    type: 'number',
    defaultValue: 1.0,
    validation: { min: 0.1, max: 100, step: 0.1 },
    advanced: true,
  },
  {
    key: 'device',
    flag: '-dev',
    fullFlag: '--device',
    category: 'general',
    label: '设备',
    description: '指定推理设备，如 CUDA0、CUDA1、Metal0、Vulkan0 等，设为 none 禁用 GPU 卸载。留空使用默认设备',
    type: 'string',
    placeholder: 'CUDA0 / Metal0 / none',
  },
  {
    key: 'split-mode',
    flag: '-sm',
    fullFlag: '--split-mode',
    category: 'general',
    label: '拆分模式',
    description: '指定多 GPU 张量拆分模式：none、layer、row',
    type: 'select',
    defaultValue: 'layer',
    options: [
      { label: '无 (none)', value: 'none' },
      { label: '按层 (layer)', value: 'layer' },
      { label: '按行 (row)', value: 'row' },
    ],
    advanced: true,
  },
  {
    key: 'cpu-mask',
    flag: '',
    fullFlag: '--cpu-mask',
    category: 'general',
    label: 'CPU 掩码',
    description: '指定 CPU 亲和性掩码，将线程绑定到特定 CPU 核心',
    type: 'string',
    placeholder: '0x0f',
    advanced: true,
  },
  {
    key: 'cpu-range',
    flag: '',
    fullFlag: '--cpu-range',
    category: 'general',
    label: 'CPU 范围',
    description: '指定 CPU 核心范围，格式：起始-结束',
    type: 'string',
    placeholder: '0-3',
    advanced: true,
  },
  {
    key: 'prio',
    flag: '',
    fullFlag: '--prio',
    category: 'general',
    label: '线程优先级',
    description: '设置计算线程的优先级，值越大优先级越高',
    type: 'number',
    defaultValue: 0,
    validation: { min: 0, max: 100, step: 1 },
    advanced: true,
  },
  {
    key: 'poll',
    flag: '',
    fullFlag: '--poll',
    category: 'general',
    label: '轮询模式',
    description: '启用基于轮询的 GPU 同步方式，替代默认的同步机制',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },

  // ============================================================
  //  采样参数 (Sampling)
  // ============================================================
  {
    key: 'temperature',
    flag: '',
    fullFlag: '--temp',
    category: 'sampling',
    label: '温度',
    description: '控制生成文本的随机性，值越高输出越多样，越低越确定',
    type: 'number',
    defaultValue: 0.8,
    validation: { min: 0, max: 5, step: 0.05 },
  },
  {
    key: 'top-k',
    flag: '',
    fullFlag: '--top-k',
    category: 'sampling',
    label: 'Top-K',
    description: '采样时只考虑概率最高的 K 个 token，降低低概率 token 被选中的可能',
    type: 'number',
    defaultValue: 40,
    validation: { min: 0, max: 200, step: 1 },
  },
  {
    key: 'top-p',
    flag: '',
    fullFlag: '--top-p',
    category: 'sampling',
    label: 'Top-P',
    description: '核采样阈值，累积概率达到 P 的 token 才被纳入采样范围',
    type: 'number',
    defaultValue: 0.9,
    validation: { min: 0, max: 1, step: 0.01 },
  },
  {
    key: 'min-p',
    flag: '',
    fullFlag: '--min-p',
    category: 'sampling',
    label: 'Min-P',
    description: '最低概率阈值，token 概率低于最高概率乘以 min-p 时被过滤',
    type: 'number',
    defaultValue: 0.05,
    validation: { min: 0, max: 1, step: 0.01 },
  },
  {
    key: 'repeat-penalty',
    flag: '',
    fullFlag: '--repeat-penalty',
    category: 'sampling',
    label: '重复惩罚',
    description: '控制重复 token 的惩罚力度，值越大越不倾向于重复',
    type: 'number',
    defaultValue: 1.0,
    validation: { min: 1, max: 2, step: 0.01 },
  },
  {
    key: 'repeat-last-n',
    flag: '',
    fullFlag: '--repeat-last-n',
    category: 'sampling',
    label: '重复检测范围',
    description: '指定检测重复的最近 N 个 token 范围，0 表示检测所有 token',
    type: 'number',
    defaultValue: 64,
    validation: { min: 0, max: 65536, step: 1 },
  },
  {
    key: 'presence-penalty',
    flag: '',
    fullFlag: '--presence-penalty',
    category: 'sampling',
    label: '存在惩罚',
    description: '对已出现的 token 施加惩罚，鼓励引入新主题（负值表示奖励）',
    type: 'number',
    defaultValue: 0.0,
    validation: { min: -2, max: 2, step: 0.01 },
  },
  {
    key: 'frequency-penalty',
    flag: '',
    fullFlag: '--frequency-penalty',
    category: 'sampling',
    label: '频率惩罚',
    description: '根据 token 出现频率施加惩罚，高频 token 被惩罚更多（负值表示奖励）',
    type: 'number',
    defaultValue: 0.0,
    validation: { min: -2, max: 2, step: 0.01 },
  },
  {
    key: 'dry-multiplier',
    flag: '',
    fullFlag: '--dry-multiplier',
    category: 'sampling',
    label: 'DRY 乘数',
    description: 'DRY 重复惩罚的乘数因子，值越大对重复短语惩罚越强',
    type: 'number',
    defaultValue: 0.0,
    validation: { min: 0, max: 10, step: 0.1 },
    advanced: true,
  },
  {
    key: 'dry-base',
    flag: '',
    fullFlag: '--dry-base',
    category: 'sampling',
    label: 'DRY 基数',
    description: 'DRY 重复惩罚的基数参数',
    type: 'number',
    defaultValue: 1.8,
    validation: { min: 1, max: 10, step: 0.1 },
    advanced: true,
  },
  {
    key: 'dry-allowed-length',
    flag: '',
    fullFlag: '--dry-allowed-length',
    category: 'sampling',
    label: 'DRY 允许长度',
    description: 'DRY 惩罚允许的重复短语最大长度，超过此长度不惩罚',
    type: 'number',
    defaultValue: 2,
    validation: { min: 0, max: 100, step: 1 },
    advanced: true,
  },
  {
    key: 'dry-penalty-last-n',
    flag: '',
    fullFlag: '--dry-penalty-last-n',
    category: 'sampling',
    label: 'DRY 惩罚范围',
    description: 'DRY 惩罚检测的最近 token 数量',
    type: 'number',
    defaultValue: 64,
    validation: { min: 0, max: 65536, step: 1 },
    advanced: true,
  },
  {
    key: 'typical-p',
    flag: '',
    fullFlag: '--typical-p',
    category: 'sampling',
    label: 'Typical-P',
    description: '局部典型性采样阈值，选择与预期分布最接近的 token',
    type: 'number',
    defaultValue: 1.0,
    validation: { min: 0, max: 1, step: 0.01 },
    advanced: true,
  },
  {
    key: 'mirostat',
    flag: '',
    fullFlag: '--mirostat',
    category: 'sampling',
    label: 'Mirostat',
    description: '启用 Mirostat 自适应采样算法，0=禁用，1=v1，2=v2',
    type: 'number',
    defaultValue: 0,
    validation: { min: 0, max: 2, step: 1 },
    options: [
      { label: '禁用', value: '0' },
      { label: 'Mirostat v1', value: '1' },
      { label: 'Mirostat v2', value: '2' },
    ],
  },
  {
    key: 'mirostat-lr',
    flag: '',
    fullFlag: '--mirostat-lr',
    category: 'sampling',
    label: 'Mirostat 学习率',
    description: 'Mirostat 的学习率（eta），影响采样策略的调整速度',
    type: 'number',
    defaultValue: 0.1,
    validation: { min: 0.01, max: 1, step: 0.01 },
    advanced: true,
  },
  {
    key: 'seed',
    flag: '-s',
    fullFlag: '--seed',
    category: 'sampling',
    label: '随机种子',
    description: '设置随机数生成器的种子，固定种子可复现相同的生成结果',
    type: 'number',
    defaultValue: -1,
    validation: { min: -1, max: 2147483647, step: 1 },
    placeholder: '-1 (随机)',
  },
  {
    key: 'ignore-eos',
    flag: '',
    fullFlag: '--ignore-eos',
    category: 'sampling',
    label: '忽略结束符',
    description: '忽略 EOS 结束符 token，使模型可以无限生成下去',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'grammar',
    flag: '',
    fullFlag: '--grammar',
    category: 'sampling',
    label: '语法规则',
    description: '指定 GBNF 语法规则字符串，限制生成文本遵循特定格式',
    type: 'string',
    placeholder: 'root ::= "hello"',
    advanced: true,
  },
  {
    key: 'grammar-file',
    flag: '',
    fullFlag: '--grammar-file',
    category: 'sampling',
    label: '语法文件',
    description: '加载 GBNF 语法规则文件，限制生成文本遵循特定格式',
    type: 'file',
    placeholder: '/path/to/grammar.gbnf',
    advanced: true,
  },
  {
    key: 'json-schema',
    flag: '-j',
    fullFlag: '--json-schema',
    category: 'sampling',
    label: 'JSON Schema',
    description: '指定 JSON Schema 约束，确保输出为合法的 JSON 格式',
    type: 'string',
    placeholder: '{ "type": "object", ... }',
    advanced: true,
  },
  {
    key: 'samplers',
    flag: '',
    fullFlag: '--samplers',
    category: 'sampling',
    label: '采样器顺序',
    description: '指定采样器的执行顺序，用分号分隔',
    type: 'string',
    defaultValue: 'penalties;dry;top_n_sigma;top_k;typ_p;top_p;min_p;xtc;temperature',
    advanced: true,
  },
  {
    key: 'xtc-probability',
    flag: '',
    fullFlag: '--xtc-probability',
    category: 'sampling',
    label: 'XTC 概率',
    description: 'XTC（排除高概率 token）采样的概率阈值',
    type: 'number',
    defaultValue: 0.0,
    validation: { min: 0, max: 1, step: 0.01 },
    advanced: true,
  },
  {
    key: 'xtc-threshold',
    flag: '',
    fullFlag: '--xtc-threshold',
    category: 'sampling',
    label: 'XTC 阈值',
    description: 'XTC 采样中高概率 token 的判定阈值',
    type: 'number',
    defaultValue: 0.1,
    validation: { min: 0, max: 1, step: 0.01 },
    advanced: true,
  },
  {
    key: 'dynatemp-range',
    flag: '',
    fullFlag: '--dynatemp-range',
    category: 'sampling',
    label: '动态温度范围',
    description: '动态温度采样的波动范围，0 表示禁用动态温度',
    type: 'number',
    defaultValue: 0.0,
    validation: { min: 0, max: 10, step: 0.1 },
    advanced: true,
  },
  {
    key: 'dynatemp-exp',
    flag: '',
    fullFlag: '--dynatemp-exp',
    category: 'sampling',
    label: '动态温度指数',
    description: '动态温度采样的指数因子',
    type: 'number',
    defaultValue: 1.0,
    validation: { min: 0.1, max: 10, step: 0.1 },
    advanced: true,
  },
  {
    key: 'logit-bias',
    flag: '-l',
    fullFlag: '--logit-bias',
    category: 'sampling',
    label: 'Logit 偏置',
    description: '指定特定 token 的 logit 偏置值，格式：token_id:偏置值',
    type: 'string',
    placeholder: '42:0.5',
    advanced: true,
  },

  // ============================================================
  //  服务器参数 (Server)
  // ============================================================
  {
    key: 'host',
    flag: '',
    fullFlag: '--host',
    category: 'server',
    label: '监听地址',
    description: '指定服务器监听的网络地址，默认 127.0.0.1 仅本地访问',
    type: 'string',
    defaultValue: '127.0.0.1',
    placeholder: '0.0.0.0 / 127.0.0.1',
  },
  {
    key: 'port',
    flag: '',
    fullFlag: '--port',
    category: 'server',
    label: '监听端口',
    description: '指定服务器监听的端口号',
    type: 'number',
    defaultValue: 8080,
    validation: { min: 1, max: 65535, step: 1 },
  },
  {
    key: 'timeout',
    flag: '-to',
    fullFlag: '--timeout',
    category: 'server',
    label: '超时时间',
    description: '设置服务器请求超时时间（秒），0 表示不超时',
    type: 'number',
    defaultValue: 0,
    validation: { min: 0, max: 3600, step: 1 },
  },
  {
    key: 'parallel',
    flag: '-np',
    fullFlag: '--parallel',
    category: 'server',
    label: '并行请求数',
    description: '指定服务器可以并行处理的请求数量（也称并行槽位数）',
    type: 'number',
    defaultValue: 1,
    validation: { min: 1, max: 256, step: 1 },
  },
  {
    key: 'cont-batching',
    flag: '-cb',
    fullFlag: '--cont-batching',
    category: 'server',
    label: '持续批处理',
    description: '启用持续批处理模式，允许动态将新请求加入当前批处理',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'no-cont-batching',
    flag: '-nocb',
    fullFlag: '--no-cont-batching',
    category: 'server',
    label: '禁用持续批处理',
    description: '禁用持续批处理模式，请求按顺序独立处理',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'embedding',
    flag: '',
    fullFlag: '--embedding',
    category: 'server',
    label: '嵌入模式',
    description: '启用嵌入向量提取模式，支持通过 API 获取文本嵌入向量',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'reranking',
    flag: '',
    fullFlag: '--reranking',
    category: 'server',
    label: '重排序模式',
    description: '启用重排序模型支持，用于信息检索场景的二次排序',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'api-key',
    flag: '',
    fullFlag: '--api-key',
    category: 'server',
    label: 'API 密钥',
    description: '设置 API 访问密钥，用于请求鉴权保护服务',
    type: 'string',
    placeholder: 'sk-xxxxxxxxxxxxxxxx',
    sensitive: true,
  },
  {
    key: 'api-key-file',
    flag: '',
    fullFlag: '--api-key-file',
    category: 'server',
    label: 'API 密钥文件',
    description: '从文件读取 API 密钥列表，每行一个密钥',
    type: 'file',
    placeholder: '/path/to/api-keys.txt',
    sensitive: true,
    advanced: true,
  },
  {
    key: 'ssl-key-file',
    flag: '',
    fullFlag: '--ssl-key-file',
    category: 'server',
    label: 'SSL 密钥文件',
    description: 'HTTPS 的 SSL 私钥文件路径',
    type: 'file',
    placeholder: '/path/to/key.pem',
    advanced: true,
  },
  {
    key: 'ssl-cert-file',
    flag: '',
    fullFlag: '--ssl-cert-file',
    category: 'server',
    label: 'SSL 证书文件',
    description: 'HTTPS 的 SSL 证书文件路径',
    type: 'file',
    placeholder: '/path/to/cert.pem',
    advanced: true,
  },
  {
    key: 'chat-template',
    flag: '',
    fullFlag: '--chat-template',
    category: 'server',
    label: '聊天模板',
    description: '指定 Jinja2 聊天模板字符串，覆盖模型自带的模板',
    type: 'string',
    placeholder: '{% for message in messages %}{{ message.content }}{% endfor %}',
    advanced: true,
  },
  {
    key: 'jinja',
    flag: '',
    fullFlag: '--jinja',
    category: 'server',
    label: 'Jinja 模板引擎',
    description: '启用 Jinja 模板引擎，支持更多模型的聊天格式（推荐开启）',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'system-prompt-file',
    flag: '-spf',
    fullFlag: '--system-prompt-file',
    category: 'server',
    label: '系统提示文件',
    description: '从文件加载系统提示词，覆盖默认的系统提示',
    type: 'file',
    placeholder: '/path/to/system-prompt.txt',
  },
  {
    key: 'mmproj',
    flag: '',
    fullFlag: '--mmproj',
    category: 'server',
    label: '多模态投影',
    description: '指定多模态投影模型文件路径，用于视觉语言模型',
    type: 'file',
    placeholder: '/path/to/mmproj.gguf',
    advanced: true,
  },
  {
    key: 'grp-attn-n',
    flag: '',
    fullFlag: '--grp-attn-n',
    category: 'server',
    label: '分组注意力 N',
    description: '设置分组注意力机制的组大小',
    type: 'number',
    validation: { min: 1, max: 1024, step: 1 },
    advanced: true,
  },
  {
    key: 'grp-attn-w',
    flag: '',
    fullFlag: '--grp-attn-w',
    category: 'server',
    label: '分组注意力 W',
    description: '设置分组注意力机制的窗口大小',
    type: 'number',
    validation: { min: 1, max: 65536, step: 1 },
    advanced: true,
  },
  {
    key: 'metrics',
    flag: '',
    fullFlag: '--metrics',
    category: 'server',
    label: '启用指标',
    description: '启用 Prometheus 指标端点，用于监控服务运行状态',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'slots',
    flag: '',
    fullFlag: '--slots',
    category: 'server',
    label: '槽位信息',
    description: '启用槽位信息端点，查看各槽位的运行状态',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'slot-save-path',
    flag: '',
    fullFlag: '--slot-save-path',
    category: 'server',
    label: '槽位保存路径',
    description: '指定槽位状态保存的目录路径',
    type: 'string',
    placeholder: '/path/to/slot-states',
    advanced: true,
  },
  {
    key: 'no-webui',
    flag: '',
    fullFlag: '--no-webui',
    category: 'server',
    label: '禁用 WebUI',
    description: '禁用内置的 Web 用户界面，仅提供 API 服务',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'no-context-shift',
    flag: '',
    fullFlag: '--no-context-shift',
    category: 'server',
    label: '禁用上下文移位',
    description: '禁用上下文移位功能，超出上下文长度时直接截断',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'no-warmup',
    flag: '',
    fullFlag: '--no-warmup',
    category: 'server',
    label: '禁用预热',
    description: '启动时跳过模型预热步骤，加快启动速度',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'spm-infill',
    flag: '',
    fullFlag: '--spm-infill',
    category: 'server',
    label: 'SPM 填充',
    description: '启用 SentencePiece 模型的填充（infill）能力',
    type: 'boolean',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'pooling',
    flag: '',
    fullFlag: '--pooling',
    category: 'server',
    label: '池化方式',
    description: '指定嵌入向量的池化方式：mean、cls、none',
    type: 'select',
    defaultValue: 'mean',
    options: [
      { label: '平均池化 (mean)', value: 'mean' },
      { label: 'CLS 池化 (cls)', value: 'cls' },
      { label: '无 (none)', value: 'none' },
    ],
    advanced: true,
  },
  {
    key: 'model-url',
    flag: '-mu',
    fullFlag: '--model-url',
    category: 'server',
    label: '模型远程 URL',
    description: '指定从远程 URL 加载模型文件',
    type: 'string',
    placeholder: 'https://example.com/model.gguf',
    advanced: true,
  },
  {
    key: 'hf-repo',
    flag: '-hfr',
    fullFlag: '--hf-repo',
    category: 'server',
    label: 'HuggingFace 仓库',
    description: '指定 HuggingFace 模型仓库 ID，自动下载模型',
    type: 'string',
    placeholder: 'Qwen/Qwen2.5-7B-GGUF',
  },
  {
    key: 'hf-file',
    flag: '-hff',
    fullFlag: '--hf-file',
    category: 'server',
    label: 'HuggingFace 文件名',
    description: '指定 HuggingFace 仓库中要下载的具体文件名',
    type: 'string',
    placeholder: 'qwen2.5-7b-q4_k_m.gguf',
  },
  {
    key: 'hf-token',
    flag: '-hft',
    fullFlag: '--hf-token',
    category: 'server',
    label: 'HuggingFace Token',
    description: '设置 HuggingFace 访问令牌，用于下载私有或受限模型',
    type: 'string',
    placeholder: 'hf_xxxxxxxxxxxx',
    sensitive: true,
  },
  {
    key: 'model-draft',
    flag: '-md',
    fullFlag: '--model-draft',
    category: 'server',
    label: '草稿模型路径',
    description: '指定推测解码中的草稿模型文件路径，用于加速推理',
    type: 'file',
    placeholder: '/path/to/draft-model.gguf',
    advanced: true,
  },
  {
    key: 'spec-type',
    flag: '',
    fullFlag: '--spec-type',
    category: 'server',
    label: '推测解码类型',
    description: '推测解码方案类型，如 draft（独立草稿模型）、draft-mtp（内置多 token 预测）、eagle3 等',
    type: 'string',
    placeholder: 'draft / draft-mtp / eagle3',
    advanced: true,
  },
  {
    key: 'spec-draft-n-max',
    flag: '',
    fullFlag: '--spec-draft-n-max',
    category: 'server',
    label: '推测最大 Token 数',
    description: '推测解码中每轮最多生成的候选 token 数量（替代旧版 --draft-max）',
    type: 'number',
    defaultValue: 16,
    validation: { min: 1, max: 100, step: 1 },
    advanced: true,
  },
];

export const PARAMETER_CATEGORIES = [
  { key: 'general' as const, label: '通用参数' },
  { key: 'sampling' as const, label: '采样参数' },
  { key: 'server' as const, label: '服务参数' },
];

export const CATEGORY_ORDER: Array<'general' | 'sampling' | 'server'> = [
  'general',
  'sampling',
  'server',
];

export function getParameterByKey(key: string): ParameterMeta | undefined {
  return PARAMETER_DEFINITIONS.find((p) => p.key === key);
}

export function getParametersByCategory(
  category: 'general' | 'sampling' | 'server',
): ParameterMeta[] {
  return PARAMETER_DEFINITIONS.filter((p) => p.category === category);
}

export function getDefaultParameterValues(): Record<string, string | number | boolean> {
  const values: Record<string, string | number | boolean> = {};
  for (const param of PARAMETER_DEFINITIONS) {
    if (param.defaultValue !== undefined) {
      values[param.key] = param.defaultValue;
    }
  }
  return values;
}