import { theme } from 'antd';
import type { ThemeConfig } from 'antd';

export const darkTheme: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  token: {
    colorPrimary: '#7c3aed',
    colorPrimaryHover: '#8b5cf6',
    colorPrimaryActive: '#6d28d9',
    colorBgBase: '#0f0f1a',
    colorBgContainer: '#1a1a2e',
    colorBgElevated: '#1e1e36',
    colorBgLayout: '#0a0a14',
    colorBorder: '#2d2d4a',
    colorBorderSecondary: '#252540',
    colorTextBase: '#e2e8f0',
    colorTextSecondary: '#94a3b8',
    colorTextTertiary: '#64748b',
    colorSuccess: '#22c55e',
    colorWarning: '#f59e0b',
    colorError: '#ef4444',
    colorInfo: '#6366f1',
    borderRadius: 8,
    fontSize: 14,
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    controlHeight: 36,
    controlHeightLG: 44,
    controlHeightSM: 28,
    lineWidth: 1,
    lineType: 'solid',
    motionDurationFast: '0.1s',
    motionDurationMid: '0.2s',
    motionDurationSlow: '0.3s',
    boxShadow: '0 1px 3px 0 rgba(0,0,0,0.3), 0 1px 2px -1px rgba(0,0,0,0.3)',
    boxShadowSecondary: '0 4px 12px 0 rgba(0,0,0,0.4)',
  },
  components: {
    Layout: {
      headerBg: '#1a1a2e',
      bodyBg: '#0a0a14',
      siderBg: '#12122a',
      triggerBg: '#1a1a2e',
      triggerHeight: 48,
    },
    Menu: {
      darkItemBg: '#12122a',
      darkItemColor: '#94a3b8',
      darkItemHoverBg: '#1e1e3a',
      darkItemHoverColor: '#e2e8f0',
      darkItemSelectedBg: '#2d1f5e',
      darkItemSelectedColor: '#a78bfa',
      itemBorderRadius: 8,
      subMenuItemBg: '#12122a',
      darkSubMenuItemBg: '#12122a',
    },
    Card: {
      colorBgContainer: '#1a1a2e',
      colorBorderSecondary: '#252540',
      paddingLG: 20,
      borderRadiusLG: 12,
    },
    Button: {
      primaryShadow: '0 1px 2px 0 rgba(124, 58, 237, 0.3)',
      defaultBorderColor: '#2d2d4a',
      defaultBg: '#1a1a2e',
      defaultColor: '#e2e8f0',
      defaultHoverBorderColor: '#7c3aed',
      defaultHoverColor: '#a78bfa',
    },
    Input: {
      colorBgContainer: '#14142a',
      colorBorder: '#2d2d4a',
      addonBg: '#1a1a2e',
      hoverBorderColor: '#7c3aed',
      activeBorderColor: '#8b5cf6',
      activeShadow: '0 0 0 2px rgba(124, 58, 237, 0.15)',
    },
    Select: {
      colorBgContainer: '#14142a',
      colorBorder: '#2d2d4a',
      optionSelectedBg: '#2d1f5e',
      hoverBorderColor: '#7c3aed',
    },
    Modal: {
      contentBg: '#1a1a2e',
      headerBg: '#1a1a2e',
      footerBg: '#1a1a2e',
    },
    Table: {
      colorBgContainer: '#1a1a2e',
      borderColor: '#252540',
      headerBg: '#14142a',
      headerColor: '#94a3b8',
      rowHoverBg: '#1e1e3a',
    },
    Tabs: {
      colorBgContainer: '#1a1a2e',
      inkBarColor: '#7c3aed',
      itemSelectedColor: '#a78bfa',
      itemHoverColor: '#8b5cf6',
    },
    Collapse: {
      colorBgContainer: '#1a1a2e',
      headerBg: '#14142a',
      contentBg: '#1a1a2e',
      colorBorder: '#252540',
    },
    Notification: {
      colorBgElevated: '#1e1e36',
    },
    Tooltip: {
      colorBgSpotlight: '#1e1e36',
    },
    Progress: {
      defaultColor: '#7c3aed',
      remainingColor: '#252540',
    },
    Switch: {
      colorPrimary: '#7c3aed',
    },
    Slider: {
      colorPrimary: '#7c3aed',
      railBg: '#252540',
      railHoverBg: '#2d2d4a',
    },
    Tag: {
      colorBgContainer: '#1a1a2e',
    },
    Badge: {},
    Spin: {
      colorPrimary: '#7c3aed',
    },
    Divider: {
      colorSplit: '#252540',
    },
    Alert: {
      colorInfoBg: '#1a1a3e',
      colorWarningBg: '#1e1e2a',
      colorErrorBg: '#1e1a1a',
      colorSuccessBg: '#1a1e1a',
    },
  },
};